version: '3.8'
services:
  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    command: -c "log_statement=all"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      zs_network:

  logsearchapi:
    image: 0chaindev/blimp-logsearchapi:staging
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    environment:
      LOGSEARCH_PG_CONN_STR: "postgres://postgres:postgres@postgres-db/postgres?sslmode=disable"
      LOGSEARCH_AUDIT_AUTH_TOKEN: 1234
      MINIO_LOG_QUERY_AUTH_TOKEN: 1234
      LOGSEARCH_DISK_CAPACITY_GB: 5
    links:
      - postgres-db
    networks:
      zs_network:

  minioserver:
    image: 0chaindev/blimp-minioserver:staging
    container_name: minioserver
    ports:
      - 9000:9000
    command: ["minio", "gateway", "zcn"]
    environment:
      MINIO_AUDIT_WEBHOOK_ENDPOINT: http://logsearchapi:8080/api/ingest?token=1234
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN: 1234
      MINIO_AUDIT_WEBHOOK_ENABLE: "on"
      MINIO_ROOT_USER: rootroot
      MINIO_ROOT_PASSWORD: rootroot
      MINIO_BROWSER: "OFF"
      MINIO_CACHE_DRIVES: "/mcache,/mcache1,/mcache2,/mcache3,/mcache4" # list of mounted cache drives or directories separated by ","
      MINIO_CACHE_EXPIRY: 90 # expiry in days
      MINIO_CACHE_COMMIT: "writeback" # to increase write throughput use writeback
      MINIO_CACHE_QUOTA: 99 # maximum permitted usage of the cache in percentage 
      MINIO_CACHE_WATERMARK_LOW: 90 # % of cache quota at which cache eviction stops
      MINIO_CACHE_WATERMARK_HIGH: 95 # % of cache quota at which cache eviction starts
      MINIO_WRITE_BACK_INTERVAL: 900 # interval in seconds
      MINIO_MAX_CACHE_FILE_SIZE: 1000000000 # max file size in bytes
      MINIO_WRITE_BACK_UPLOAD_WORKERS: 20
      MINIO_UPLOAD_QUEUE_TH: 10
    links:
      - logsearchapi:logsearchapi
    volumes:
      - ~/.zcn:/root/.zcn
      - /mnt/mcache:/mcache
      - /mnt/mcache1:/mcache1
      - /mnt/mcache2:/mcache2
      - /mnt/mcache3:/mcache3
      - /mnt/mcache4:/mcache4
    networks:
      zs_network:

  minioclient:
    image: 0chaindev/blimp-clientapi:staging
    container_name: minioclient
    depends_on:
      - minioserver
    ports:
      - 3001:3001
    environment:
      MINIO_SERVER: "minioserver:9000"
    networks:
      zs_network:
  
volumes:
  db:
    driver: local

networks:
  zs_network:
    driver: bridge
